language: ruby
cache: bundler
sudo: false

before_install: gem install bundler

rvm:
  - 2.5.1

gemfile:
  - gemfiles/rails_5_1.gemfile

env:
  global:
    - RAILS_ENV=test
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgresql

script:
  - bundle exec rake --trace db:migrate
  - bundle exec rake

before_script:
  - mysql -e 'create database devise_token_auth_test'
  - psql -c 'create database devise_token_auth_test' -U postgres

addons:
  postgresql: "9.4"
